package com.myspace.jpaprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PERSON_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PERSON_ID_SEQ", name = "PERSON_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String firstName;

	private java.lang.String lastName;

	public Person() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public Person(java.lang.Long id, java.lang.String firstName,
			java.lang.String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}
	
	@Override
    public java.lang.String toString() {
        return "Person [id=" + id + ", firstName=" + firstName + ", lasteName=" + lastName + "]";
    }

}